---
title: "TE_vst_ggplot"
output: html_document
params:
  project: P20_testis_SE
---

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(DESeq2)
library(ggrastr)
library(stringr)
library("vsn")
#if (!require("RColorBrewer")) {
#install.packages("RColorBrewer")
library(RColorBrewer)
#}
```

```{r}
TE_list_rodrep <- read.table("/Users/ykabayam/Documents/RNA-seq/Ansgar_Spocd1/header_info_rodrep.txt", header = TRUE)

Control1 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_WTA_rodrep_hit.txt", header = FALSE)
Control2 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_WTB_rodrep_hit.txt", header = FALSE)
Control3 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_WTC_rodrep_hit.txt", header = FALSE)
Spocd1_1 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_Spocd19_rodrep_hit.txt", header = FALSE)
Spocd1_2 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_Spocd110_rodrep_hit.txt", header = FALSE)
Spocd1_3 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_Spocd111_rodrep_hit.txt", header = FALSE)
Miwi2_1 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_Miwi2802_rodrep_hit.txt", header = FALSE)
Miwi2_2 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_Miwi2810_rodrep_hit.txt", header = FALSE)
Miwi2_3 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_Miwi2811_rodrep_hit.txt", header = FALSE)
Tex15_1 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_Tex15297_rodrep_hit.txt", header = FALSE)
Tex15_2 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_Tex15298_rodrep_hit.txt", header = FALSE)
Tex15_3 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_Tex15301_rodrep_hit.txt", header = FALSE)
C19_1 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_C19221_rodrep_hit.txt", header = FALSE)
C19_2 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_C19224_rodrep_hit.txt", header = FALSE)
C19_3 <- read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/out_bowtie2/count_C19225_rodrep_hit.txt", header = FALSE)

colnames(Control1)=c("TE", "Control_1")
colnames(Control2)=c("TE", "Control_2")
colnames(Control3)=c("TE", "Control_3")
colnames(Miwi2_1)=c("TE", "Miwi2_1")
colnames(Miwi2_2)=c("TE", "Miwi2_2")
colnames(Miwi2_3)=c("TE", "Miwi2_3")
colnames(Spocd1_1)=c("TE", "Spocd1_1")
colnames(Spocd1_2)=c("TE", "Spocd1_2")
colnames(Spocd1_3)=c("TE", "Spocd1_3")
colnames(Tex15_1)=c("TE", "Tex15_1")
colnames(Tex15_2)=c("TE", "Tex15_2")
colnames(Tex15_3)=c("TE", "Tex15_3")
colnames(C19_1)=c("TE", "C19_1")
colnames(C19_2)=c("TE", "C19_2")
colnames(C19_3)=c("TE", "C19_3")

master_ctrl <- left_join(Control1, Control2) %>% left_join(Control3)
master_M <- left_join(Miwi2_1, Miwi2_2) %>% left_join(Miwi2_3)
master_S <- left_join(Spocd1_1, Spocd1_2) %>% left_join(Spocd1_3)
master_T <- left_join(Tex15_1, Tex15_2) %>% left_join(Tex15_3)
master_C19 <- left_join(C19_1, C19_2) %>% left_join(C19_3)

master_all <- left_join(master_ctrl, master_M) %>% left_join(master_S) %>% left_join(master_T) %>% left_join(master_C19)
master_all[is.na(master_all)] <- 0
#write.table(master_all, file = "/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/master_all_TE.txt", sep="\t", col.names=T, row.names=F, quote=F)
```

```{r}
TEcounts=read.table("/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/master_all_TE.txt", header=TRUE,row.names=1,fill=TRUE,sep="\t")
TEcounts <- select(TEcounts, 1:9, 13:15)
#mircounts=mircounts[,3:ncol(mircounts)]
conds=as.factor(c("ctrl","ctrl","ctrl","Miwi2","Miwi2","Miwi2","Spocd1","Spocd1","Spocd1","Gabri","Gabri","Gabri"))

classcol=rainbow(length(levels(class)))
names(classcol)=sort(levels(class))

brewer.pal(length(unique(conds)),"Accent")
cond_colours=brewer.pal(length(unique(conds)),"Accent")[as.factor(conds)]
#cond_colours= rainbow(length(unique(conds)))[as.factor(conds)]
names(cond_colours)=conds
```

```{r}
barplot(apply(TEcounts,2,sum), las=2,col=cond_colours)
legend("topright",levels((conds)),cex=0.6,fill=cond_colours[levels(conds)])
```

```{r}
coldata = as.data.frame(t(t(conds)))
rownames(coldata)=colnames(TEcounts)
colnames(coldata)='condition'

dds <- DESeqDataSetFromMatrix(countData = TEcounts, colData = coldata, design = ~ condition)
dds <- estimateSizeFactors(dds)
dds <- estimateDispersions(dds)
dds <- nbinomWaldTest(dds)
cds=dds

counts_table=counts(dds,normalized=TRUE)
```

```{r}
siglist=c()
hitarray=c()
comparisons=0
for (i in 1:length(sort(unique(conds)))){
  for (j in i:length(sort(unique(conds)))){
    if( i != j){
      comparisons=comparisons+1
      print(paste(i,j,"comparison ",comparisons))
      c1=as.character(sort(unique(conds))[i]);
      c2=as.character(sort(unique(conds))[j]);
      print(paste(c1,"versus",c2))
      
      contrastname=paste(c1,"versus",c2)

      
      res <- results(dds, contrast=c("condition", c2, c1))
      res <- res[order(res$padj),]
      
      
      res_output=res;
      res_output=res_output[rownames(counts(dds)),]
      
      for(z in 1:length(colnames(res_output))){
        colnames(res_output)[z]=paste(c1,"_v_",c2,"_",colnames(res_output)[z],sep="")
      }
      counts_table=data.frame(counts_table,res_output)
      
      # Volcano Plot and Heatmaps of significant hits.
      sig_p=0.01
      sig_lfc=1
      z=res
      hitlist = rownames(res[(abs(z$log2FoldChange) > sig_lfc) & (z$padj <= sig_p) & (!is.na(z$log2FoldChange)) & (!is.na(z$padj)),])
      hitlistids = (abs(z$log2FoldChange) > sig_lfc) & (z$padj <= sig_p) & (!is.na(z$log2FoldChange)) & (!is.na(z$padj))
      
      hitarray[[comparisons]]=hitlist
      
      hitlistup = rownames(res[((z$log2FoldChange) > sig_lfc) & (z$padj <= sig_p) & (!is.na(z$log2FoldChange)) & (!is.na(z$padj)),])
      hitlistdown = rownames(res[((z$log2FoldChange) < -sig_lfc) & (z$padj <= sig_p) & (!is.na(z$log2FoldChange)) & (!is.na(z$padj)),])
      
      siglist=c(siglist,hitlist)

m1=apply(counts(dds,normalized=TRUE)[,conds==c1],1,median)
      m2=apply(counts(dds,normalized=TRUE)[,conds==c2],1,median)
      
      plot(log2(m1+1),log2(m2+1),xlab=c1,ylab=c2,pch=19,cex=0.5,col="grey",main=paste(contrastname,"Pairwise Plot RAW"))
      if (length(hitlist)>=1){
      points(log2(m1+1)[hitlist],log2(m2+1)[hitlist],pch=19,cex=0.5,col="red",main=paste(contrastname,"Pairwise Plot RAW"))
      text(log2(m1+1)[hitlist],log2(m2+1)[hitlist],labels=hitlist,cex=0.4,pos=2)
#      text(log2(m1+1)[hitlist[grep("IAP",hitlist)]],log2(m2+1)[hitlist[grep("IAP",hitlist)]],labels=hitlist[grep("IAP",hitlist)],cex=0.4,pos=2,col="red")
#      legend("topleft",sort(unique(as.character(class[hitlist]))),cex=0.5,fill=classcol[sort(unique(as.character(class[hitlist])))],bty="n")
      }
#      legend("topright",paste(length(hitlistdown),"sig.\n genes above line"),cex=0.4)
#      legend("bottomright",paste(length(hitlistup),"sig.\n genes above line"),cex=0.4)
      abline(a=0,b=1,lty=2,col="red",lwd=0.5)
      
          }
  }
}
   
```

#Select specific TEs for heatmap (C19, Spocd1, Miwi2)
```{r}
#Add TE species as column to DESeq result table
counts_table$TE <- row.names(counts_table)
heatmap <- select(counts_table, "ctrl_v_Gabri_log2FoldChange", "ctrl_v_Spocd1_log2FoldChange","ctrl_v_Miwi2_log2FoldChange", "TE")
colnames(heatmap) = c("C19", "Spocd1", "Miwi2", "TE")
heatmap_2 <- filter(heatmap, TE %in% c("L1Md_Gf_5end", "L1MdTf_II", "L1MdTf_I", "L1MdA_I", "L1_MM", "L1MdA_II", "L1MdA_III", "L1MdGf_II", "L1MdTf_III", "L1MdGf_I", "IAPA_MM","RLTR1IAP_MM","IAPEZI","MMERVK10C","IAPLTR1_Mm","IAPLTR1a_I_MM","IAP5-Mm_I","ERVB4_1B-I_MM","IAPEY5_I","IAPEY4_LTR"))

heatmap_plot <- pivot_longer(heatmap_2, cols=1:3, names_to = "sample", values_to ="log2_FC")
heatmap_plot_2 <- transform(heatmap_plot, TE= factor(TE, levels = c("IAPEY4_LTR", "IAPEY5_I", "ERVB4_1B-I_MM", "IAP5-Mm_I", "IAPLTR1a_I_MM", "IAPLTR1_Mm", "MMERVK10C", "IAPEZI", "RLTR1IAP_MM", "IAPA_MM", "L1MdGf_I", "L1MdTf_III", "L1MdGf_II", "L1MdA_III", "L1MdA_II", "L1_MM", "L1MdA_I", "L1MdTf_I","L1MdTf_II", "L1Md_Gf_5end")))
heatmap_plot_3 <- transform(heatmap_plot_2, sample=factor(sample, levels =c("Miwi2", "Spocd1", "C19")))
```

```{r}
ggplot(data = heatmap_plot_3, aes(x = sample, y = TE)) + 
  geom_tile(aes(fill = log2_FC)) + theme_classic() + 
  scale_fill_gradient(low = "white", high = "blue", limits=c(0, 4.5)) +
  coord_fixed() +
  scale_y_discrete(limits = rev(levels(as.numeric(heatmap_plot$log2_FC))))

ggsave(paste("/Users/ykabayam/Documents/R_script/RNA-seq/", params$project, "/heatmap_P20testis_C19_Spocd1_Miwi2_TE_log2FC.pdf", sep = ""), width=5, height = 7)
```






```{r}
#Add TE species as column to DESeq result table
counts_table$TE <- row.names(counts_table)

heatmap <- select(counts_table, "ctrl_v_Gabri_log2FoldChange", "ctrl_v_Spocd1_log2FoldChange","ctrl_v_Miwi2_log2FoldChange")
heatmap <- heatmap %>% mutate(Mean_Control=rowMeans(heatmap[,c(1,2,3)])) %>% mutate(Mean_Miwi2_KO=rowMeans(heatmap[,c(4,5,6)])) %>% mutate(Mean_Gabri_KO=rowMeans(heatmap[,c(7,8,9)])) %>% mutate(FC_Miwi2 = Mean_Miwi2_KO/Mean_Control) %>% mutate(FC_Gabri = Mean_Gabri_KO/Mean_Control)


counts_pval_Miwi2 <- dplyr::select(counts_table, "TE", "ctrl_v_Miwi2_log2FoldChange", "ctrl_v_Miwi2_padj")
counts_pval_Miwi2_ed <- filter(counts_pval_Miwi2, ctrl_v_Miwi2_log2FoldChange >= 1 & ctrl_v_Miwi2_padj < 0.01 | ctrl_v_Miwi2_log2FoldChange <= -1 & ctrl_v_Miwi2_padj < 0.01) %>% mutate(class = "Miwi2_KO")
counts_pval_Miwi2_ed$TE <- factor(counts_pval_Miwi2_ed$TE, levels = counts_pval_Miwi2_ed$TE[order(counts_pval_Miwi2_ed$ctrl_v_Miwi2_log2FoldChange, decreasing = F)])
write.table(counts_pval_Miwi2_ed, file = "/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/Miwi2_Significant_TE_vC19.txt", sep="\t", col.names=T, row.names=F, quote=F)

counts_pval_Gabri <- dplyr::select(counts_table, "TE", "ctrl_v_Gabri_log2FoldChange", "ctrl_v_Gabri_padj")
counts_pval_Gabri_ed <- filter(counts_pval_Gabri, ctrl_v_Gabri_log2FoldChange >= 1 & ctrl_v_Gabri_padj < 0.01 | ctrl_v_Gabri_log2FoldChange <= -1 & ctrl_v_Gabri_padj < 0.01) %>% mutate(class = "Gabri_KO")
counts_pval_Gabri_ed$TE <- factor(counts_pval_Gabri_ed$TE, levels = counts_pval_Gabri_ed$TE[order(counts_pval_Gabri_ed$ctrl_v_Gabri_log2FoldChange, decreasing = F)])
write.table(counts_pval_Gabri_ed, file = "/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/Gabri_Significant_TE_vMiwi2.txt", sep="\t", col.names=T, row.names=F, quote=F)

combine <- left_join(counts_pval_Miwi2_ed, counts_pval_Gabri_ed)
combine$TE <- factor(combine$TE, levels = combine$TE[order(combine$ctrl_v_Miwi2_log2FoldChange, decreasing = F)])
```

#Arrange TEs for heatmap regardless of significancy (C19, Spocd1, Miwi2)
```{r}
heatmap <- select(counts_table, 1:9)
heatmap$TE <- row.names(heatmap)
heatmap <- heatmap %>% mutate(Mean_Control=rowMeans(heatmap[,c(1,2,3)])) %>% mutate(Mean_Miwi2_KO=rowMeans(heatmap[,c(4,5,6)])) %>% mutate(Mean_Gabri_KO=rowMeans(heatmap[,c(7,8,9)])) %>% mutate(FC_Miwi2 = Mean_Miwi2_KO/Mean_Control) %>% mutate(FC_Gabri = Mean_Gabri_KO/Mean_Control)

counts_Miwi2 <- dplyr::select(counts_table, "TE", "ctrl_v_Miwi2_log2FoldChange")
counts_Miwi2_ed <- filter(counts_pval_Miwi2, ctrl_v_Miwi2_log2FoldChange >= 1) %>% mutate(class = "Miwi2_KO")
counts_Miwi2_ed$TE <- factor(counts_Miwi2_ed$TE, levels = counts_Miwi2_ed$TE[order(counts_Miwi2_ed$ctrl_v_Miwi2_log2FoldChange, decreasing = F)])
write.table(counts_Miwi2_ed, file = "/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/Miwi2_log2FC1_TE_vC19_nopval.txt", sep="\t", col.names=T, row.names=F, quote=F)

counts_Gabri <- dplyr::select(counts_table, "TE", "ctrl_v_Gabri_log2FoldChange")
counts_Gabri_ed <- filter(counts_pval_Gabri, ctrl_v_Gabri_log2FoldChange >= 0) %>% mutate(class = "Gabri_KO")
counts_Gabri_ed$TE <- factor(counts_Gabri_ed$TE, levels = counts_Gabri_ed$TE[order(counts_Gabri_ed$ctrl_v_Gabri_log2FoldChange, decreasing = F)])
write.table(counts_Gabri_ed, file = "/Users/ykabayam/Documents/RNA-seq/P20_testis_SE/Gabri_log2FC0_TE_vMiwi2_nopval.txt", sep="\t", col.names=T, row.names=F, quote=F)

combine <- left_join(counts_Miwi2_ed, counts_Gabri_ed)
combine$TE <- factor(combine$TE, levels = combine$TE[order(combine$ctrl_v_Miwi2_log2FoldChange, decreasing = F)])
```

#Heatmap with log2(fold change)
```{r}
#plot <- filter(counts_pval_Gabri_ed, ctrl_v_Gabri_log2FoldChange > 0)
ggplot(data = counts_Gabri_ed, aes(x = class, y = TE)) + 
  geom_tile(aes(fill = ctrl_v_Gabri_log2FoldChange)) + theme_classic() + 
  scale_fill_gradient(low = "white", high = "blue", limits=c(0, 4.5))
ggsave("/Users/ykabayam/Documents/R_script/RNA-seq/P20_testis_SE/P20tes_heatmap_TE_Gabri_log2FC_vMiwi2.pdf", width=5)
```

#Heatmap with raw fold change value with p-value
```{r}
counts_pval_Miwi2 <- dplyr::select(heatmap, "TE", "FC_Miwi2", "ctrl_v_Miwi2_padj")
counts_pval_Miwi2_ed <- filter(counts_pval_Miwi2, FC_Miwi2 > 1 & ctrl_v_Miwi2_padj < 0.01) %>% mutate(class = "Miwi2_KO")
counts_pval_Miwi2_ed$TE <- factor(counts_pval_Miwi2_ed$TE, levels = counts_pval_Miwi2_ed$TE[order(counts_pval_Miwi2_ed$FC_Miwi2, decreasing = F)])

counts_pval_Gabri <- dplyr::select(heatmap, "TE", "FC_Gabri", "ctrl_v_Gabri_padj")
counts_pval_Gabri_ed <- filter(counts_pval_Gabri, FC_Gabri > 1 & ctrl_v_Gabri_padj < 0.01) %>% mutate(class = "Gabri_KO")
counts_pval_Gabri_ed$TE <- factor(counts_pval_Gabri_ed$TE, levels = counts_pval_Gabri_ed$TE[order(counts_pval_Gabri_ed$FC_Gabri, decreasing = F)])
```

#Heatmap with raw fold change value with p-value
```{r}
ggplot(data = counts_pval_Miwi2_ed, aes(x = class, y = TE)) + 
  geom_tile(aes(fill = FC_Miwi2)) + theme_classic() + scale_fill_gradient(low = "white", high = "black", limits=c(0, 25))
#ggsave("/Users/ykabayam/Documents/R_script/RNA-seq/P20_testis_SE/P20tes_heatmap_TE_Miwi2_p0.01_rawFC_black.pdf", width=5)
```


