---
title: "Visualise annotated small RNA"
author: "Yuka Kabayama"
date: "17/4/2019"
output: html_document
---

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggrastr)
library(stringr)
```

```{r}
table <- read.table("/Users/ykabayam/Documents/sRNA-seq/Ansgar/Processed/v3/view/spocd1_sRNA_full_table_v3.txt", sep="\t", stringsAsFactors = FALSE, header = FALSE)

colnames(table) <- c("sequence", "length", "count", "subclass", "subfamily", "family", "class", "sample", "condition", "normF")
```

#Data arrangement for composition (stacked bar chart)
```{r}
pirna <- table %>% dplyr::select(sequence, length, count, sample, subclass, subfamily, family, condition) %>% filter(length >= 25, length <= 30) %>% unique()

#individual sample
count_group <- pirna %>% group_by(sample, family) %>% summarise(count_family = sum(count)) %>% filter(!family %in% c("LINE?", "LTR?", "SINE?", "miRNA", "tegRNA")) %>% ungroup()
count_group$family2 <- factor(count_group$family, levels = c("others", "nrRNA", "ncRNA", "genes", "LINE", "SINE", "LTR"))

#merged replicates
count_group_con <- pirna %>% group_by(condition, family) %>% summarise(count_family = sum(count)) %>% filter(!family %in% c("LINE?", "LTR?", "SINE?", "miRNA", "tegRNA")) %>% ungroup()
count_group_con$family2 <- factor(count_group_con$family, levels = c("others", "nrRNA", "ncRNA", "genes", "LINE", "SINE", "LTR"))

#individual sample, devide LTR into IAP or non-IAP
count_group2 <- pirna %>% group_by(sample, family) %>% summarise(count_family = sum(count)) %>% filter(!family %in% c("LINE?", "LTR", "LTR?", "SINE?", "miRNA", "tegRNA")) %>% ungroup()

count_IAP <- pirna %>% filter(family == "LTR", stringr::str_detect(subclass, "IAP")) %>% group_by(sample, family) %>% summarise(count_family = sum(count)) %>% mutate(family= "IAP")
count_non_IAP <- pirna %>% filter(family == "LTR", !stringr::str_detect(subclass, "IAP")) %>% group_by(sample, family) %>% summarise(count_family = sum(count))

merge <- bind_rows(count_group2, count_IAP, count_non_IAP)
merge$family2 <- factor(merge$family, levels = c("others", "nrRNA", "ncRNA", "genes", "LINE", "SINE", "LTR", "IAP"))

#merged replicates WT vs KO
count_group_con2 <- pirna %>% group_by(condition, family) %>% summarise(count_family = sum(count)) %>% filter(!family %in% c("LINE?", "LTR", "LTR?", "SINE?", "miRNA", "tegRNA")) %>% ungroup()

count_IAP_con <- pirna %>% filter(family == "LTR", stringr::str_detect(subclass, "IAP")) %>% group_by(condition, family) %>% 
  summarise(count_family = sum(count)) %>% mutate(family= "IAP")
count_non_IAP_con <- pirna %>% filter(family == "LTR", !stringr::str_detect(subclass, "IAP")) %>% group_by(condition, family) %>% 
  summarise(count_family = sum(count))

merge_con <- bind_rows(count_group_con2, count_IAP_con, count_non_IAP_con)
merge_con$family2 <- factor(merge_con$family, levels = c("others", "nrRNA", "ncRNA", "genes", "LINE", "SINE", "LTR", "IAP"))
```

#Composition of annotated piRNAs 
```{r}
p <- ggplot(data=merge, aes(x=sample, y=count_family, fill=family2)) + 
  geom_bar(colour = "black", stat = "identity", position = "fill", width = 0.8) + 
  theme_classic(base_size = 12) + scale_fill_brewer() +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Sample", y = "Ratio", title = "Composition of mapped piRNAs (25-30 nt)")
p
```

```{r}
p <- ggplot(data=merge_con, aes(x=condition, y=count_family, fill=family2)) +
  geom_bar(colour = "black", stat = "identity", position = "fill", width = 0.5) + 
  theme_classic(base_size = 12) +
  scale_fill_brewer() +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Sample", y = "Ratio", title = "Composition of mapped piRNAs (25-30 nt)")
p
```

#Data arrangement for length distribution (line chart)
```{r}
unique_read <- table %>% dplyr::select(sequence, length, count, sample, condition, normF) %>% filter(length >= 18, length <= 32) %>% unique()

length_dist_norm <- unique_read %>% group_by(sample) %>% summarise(normalize = sum(count)) %>% ungroup() %>% dplyr::select(sample, normalize)

length_dist <- unique_read %>% group_by(length, sample, condition) %>% summarise(count_length = sum(count))

length_summary <- length_dist %>% left_join(length_dist_norm) %>% rowwise() %>% 
                         mutate(freq = count_length/normalize) %>% dplyr::select(length, sample, freq, condition)

unique_read_TE <- table %>% filter(class == "teRNA") %>% select(sequence, length, count, sample, condition) %>% filter(length >= 18, length <= 32) %>% unique()

length_dist_TE <- unique_read_TE %>% group_by(length, sample, condition) %>% summarise(count_length = sum(count))

length_dist_TE_norm <- unique_read_TE %>% group_by(sample) %>% summarise(normalize = sum(count)) %>% ungroup() %>% select(sample, normalize)

unique_read_TE_summary <- length_dist_TE %>% left_join(length_dist_TE_norm) %>% rowwise() %>% 
                         mutate(freq = count_length/normalize) %>% select(length, sample, freq, condition)

unique_read_IAP <- table %>% filter(family == "LTR", str_detect(subclass, "IAP")) %>% select(sequence, length, count, sample, condition) %>% filter(length >= 18, length <= 32) %>% unique()

length_dist_IAP <- unique_read_IAP %>% group_by(length, sample, condition) %>% summarise(count_length = sum(count))

length_IAP_summary <- length_dist_IAP %>% left_join(length_dist_TE_norm) %>% rowwise() %>% 
                         mutate(freq = count_length/normalize) %>% select(length, sample, freq, condition)


unique_read_LINE <- table %>% filter(family == "LINE") %>% select(sequence, length, count, sample, condition) %>% filter(length >= 18, length <= 32) %>% unique()

length_dist_LINE <- unique_read_LINE %>% group_by(length, sample, condition) %>% summarise(count_length = sum(count))

length_LINE_summary <- length_dist_LINE %>% left_join(length_dist_TE_norm) %>% rowwise() %>% 
                         mutate(freq = count_length/normalize) %>% select(length, sample, freq, condition)
```

#Frequency -individual Length distribution
```{r}
p <- ggplot(data=XXX_summary, aes(x=length, y=freq, fill = sample, colour = sample)) + 
  theme_classic(base_size = 15) +
  geom_line(size = 0.75, stat="identity") + 
  scale_colour_manual(values = c("#000000", "#333333", "#555555", "#99CCFF", "#3399CC", "#0099CC")) +
  scale_y_continuous(expand = c(0,0)) + scale_x_continuous(limits = c(18, 32), breaks = seq(18, 32, 1)) +
  labs(x = "Length", y = "Relative amount of sRNAs", title = "Length distribution of XXX small RNAs")
p
```

#Frequency -merged Length distribution with error bar
```{r}
p <- ggplot(data=XXX_summary, aes(x=length, y=freq, fill = condition, colour = condition)) +
  theme_classic(base_size = 15) +
  stat_summary(geom = "line", fun.y = mean, size = 0.75) +
  stat_summary(geom="errorbar", fun.data = mean_se, size = 0.5, width = 0.2) +
  scale_y_continuous(expand = c(0,0)) + scale_x_continuous(limits = c(18, 32), breaks = seq(18, 32, 1)) +
  scale_colour_manual(values = c("#000000", "#3399CC")) +
  labs(x = "Length", y = "Relative amount of sRNAs", title = "Length distribution of XXX small RNAs")
p
```

#t-test
```{r}
length <- length_summary %>% filter(length == 18)
t.test(length$freq[length$condition=="Control_S"], length$freq[length$condition=="Spocd1_KO"], var.equal = T)
```

#Pirwise plot of annotated piRNA (total count > 10)
```{r eval=FALSE, include=FALSE}
classes <- pirna %>% group_by(sequence, condition) %>% summarise(count_sum = sum(count)) %>%
                     filter(count_sum > 10)

spread <- classes %>% unique() %>% spread(condition, count_sum) 
spread[is.na(spread)]<-0
```

```{r}
ggplot(spread, aes(x=log(Control), y=log(Spocd1_KO))) + 
  geom_point_rast(size=1, alpha=0.5) + 
  stat_smooth(method = "lm", se = FALSE, colour = "black", size = 0.5) + 
  geom_abline(intercept = 0, slope = 1, color="red") + theme_classic() +
  labs(x = "log2 piRNA count Control", y = "log2 piRNA count Spocd1 KO", title = "Pairwise plot of piRNA (25-30 nt, >10 count)")
```

#Pearson's correlation
```{r}
x <- spread %>% ungroup() %>% dplyr::select(c(Control_S))
y <- spread %>% ungroup() %>% dplyr::select(c(Spocd1_KO))

cor(x, y)
```

